version: "3"
services:
  php:
    build: ./docker/php
    volumes:
      - ./website:/website
  nginx:
    image: nginx:1.18-alpine
    ports:
      - "8080:80"
    volumes:
      - ./website:/website
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
